# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dağıtım
email: hi@linuxkafasi.org
description: >-
  Newset and easeist way to check your favorite Linux, BSD, Unix distribution, open-source packages and compare them.
baseurl: ""
url: "https://dagitim.linuxkafasi.org"

collections:
  distros:
    output: true
    permalink: /:path/

# Build settings
markdown: kramdown
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- node_modules
- vendor
